// expected exit code is 5
 
Integer foo(Integer value) {
  return value;
}

exit(foo(5));